#!/bin/bash
set -euo pipefail  # Exit on any error, undefined variable, or pipe failure

# File: .claude/hooks/pre-compact.md
# FULLY AUTOMATED continuation system - ZERO manual steps required

# Error logging
exec 2>> .claude/hooks/pre-compact.log
echo "=== PreCompact hook starting at $(date) ===" >&2

TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
DATE_READABLE=$(date +"%Y-%m-%d %H:%M:%S")
BACKUP_FILE="plans/continuation-prompts/continue-${TIMESTAMP}.md"

# Ensure directories exist
mkdir -p plans/continuation-prompts
mkdir -p .serena/memories
mkdir -p .claude/hooks

echo "🔄 Context window nearly full - activating FULL AUTOMATION..."
echo ""

# ============================================================================
# STEP 1: Gather current state
# ============================================================================

GIT_STATUS=$(git status 2>&1)
GIT_COMMITS=$(git log --oneline -10 2>&1)
GIT_DIFF_STAT=$(git diff --stat 2>&1)
GIT_BRANCH=$(git branch --show-current 2>&1)

# Get active plans
ACTIVE_PLANS=""
if [ -d "plans/ACTIVE" ]; then
    ACTIVE_PLANS=$(find plans/ACTIVE -name "*.md" -type f 2>/dev/null | while read plan; do
        echo "### $(basename "$plan")"
        head -30 "$plan"
        echo ""
    done)
fi

# Get other non-completed plans
OTHER_PLANS=$(find plans/ -maxdepth 1 -name "*.md" -type f ! -name "*completed*" ! -name "*COMPLETED*" 2>/dev/null | head -3 | while read plan; do
    echo "- $(basename "$plan")"
done)

# Get recent plan modifications
RECENT_PLANS=$(find plans/ -name "*.md" -type f -mtime -7 ! -path "*/COMPLETED/*" ! -path "*/completed/*" 2>/dev/null | head -5 | while read plan; do
    MOD_DATE=$(stat -c %y "$plan" 2>/dev/null | cut -d' ' -f1)
    echo "- $plan (modified: $MOD_DATE)"
done)

# ============================================================================
# STEP 2: Create continuation prompt for clipboard/backup
# ============================================================================

cat > "$BACKUP_FILE" <<PROMPT_EOF
# Continue Commission Tracker Project

**Session Context Filled:** $DATE_READABLE
**Branch:** $GIT_BRANCH

---

## Current Git State

### Status
\`\`\`
$GIT_STATUS
\`\`\`

### Recent Commits
\`\`\`
$GIT_COMMITS
\`\`\`

### Uncommitted Changes
\`\`\`
$GIT_DIFF_STAT
\`\`\`

---

## Active Plans

$ACTIVE_PLANS

## Other Active Plans
$OTHER_PLANS

## Recently Modified Plans
$RECENT_PLANS

---

## Project Context

- **Name:** Insurance Sales KPI Tracking System
- **Stack:** React 19.1, TypeScript, Supabase/Postgres, TanStack Router/Query/Form
- **Purpose:** Track policies, calculate KPIs, manage commissions, monitor expenses

## Critical Rules (From CLAUDE.md)

1. **ZERO LOCAL STORAGE** - All data in Supabase, never localStorage/sessionStorage
2. **Single Migration Directory** - Only \`supabase/migrations/\`
3. **Test Before Complete** - Run typecheck and test all changes
4. **Use Symbolic Tools** - Avoid reading entire files
5. **No Placeholder UI** - Every feature must be fully functional
6. **Update Plans** - Move to completed/ when done

## Next Steps

[Review active plans above and continue from where we left off]

Please read the \`ACTIVE_SESSION_CONTINUATION\` memory for detailed continuation context, or continue based on the active plans listed above.

---

*Auto-generated by PreCompact hook at $DATE_READABLE*
PROMPT_EOF

if [ -f "$BACKUP_FILE" ]; then
    echo "✅ Backup file created successfully: $BACKUP_FILE" >&2
else
    echo "❌ ERROR: Failed to create backup file!" >&2
    exit 1
fi

# ============================================================================
# STEP 3: Write to Serena memory for AUTO-RESUME (ZERO-TOUCH)
# ============================================================================

echo "Writing continuation memory..." >&2

cat > ".serena/memories/ACTIVE_SESSION_CONTINUATION.md" <<MEMORY_EOF
# Active Session Continuation

**Last Session Ended:** $DATE_READABLE
**Reason:** Context window filled (auto-compact)
**Branch:** $GIT_BRANCH

---

## Quick Summary

This memory contains the state of the last session that filled up the context window.

**When you see this memory in a new conversation:**
1. Acknowledge you found an active session from [$DATE_READABLE]
2. Summarize the current state based on git status and active plans below
3. Ask if the user wants to continue from there or start fresh
4. If continuing, review active plans and proceed with next steps

---

## Git State at Session End

### Branch
\`\`\`
$GIT_BRANCH
\`\`\`

### Status
\`\`\`
$GIT_STATUS
\`\`\`

### Recent Commits (Last 10)
\`\`\`
$GIT_COMMITS
\`\`\`

### Uncommitted Changes
\`\`\`
$GIT_DIFF_STAT
\`\`\`

---

## Active Plans at Session End

$ACTIVE_PLANS

## Other Active Plans
$OTHER_PLANS

## Recently Modified Plans (Last 7 Days)
$RECENT_PLANS

---

## Project Reminders

- ZERO LOCAL STORAGE - all data in Supabase
- Single migration directory: supabase/migrations/
- Test before completing tasks
- Use symbolic tools to avoid reading entire files
- No placeholder UI features
- Update plan files and move to completed/ when done

---

## How to Continue

1. **Check if continuation is still relevant** - Look at timestamp above
2. **Review active plans** - See what was being worked on
3. **Check git status NOW** - Compare to status above to see what changed
4. **Resume work** - Continue from active plans or ask user for direction

---

**Note:** This memory is auto-generated by the PreCompact hook and will be overwritten on next context fill.

Delete this memory (or rename it to ACTIVE_SESSION_CONTINUATION_ARCHIVED_$TIMESTAMP) when the session is complete.
MEMORY_EOF

if [ -f ".serena/memories/ACTIVE_SESSION_CONTINUATION.md" ]; then
    echo "✅ Memory written successfully: .serena/memories/ACTIVE_SESSION_CONTINUATION.md" >&2
    echo "✅ Memory written: .serena/memories/ACTIVE_SESSION_CONTINUATION.md"
else
    echo "❌ ERROR: Failed to write memory file!" >&2
    exit 1
fi

# ============================================================================
# STEP 4: Copy to Windows clipboard for IMMEDIATE use
# ============================================================================

if command -v clip.exe &> /dev/null; then
    cat "$BACKUP_FILE" | clip.exe
    echo "✅ Continuation prompt copied to Windows clipboard"
    CLIPBOARD_SUCCESS=true
else
    echo "⚠️  clip.exe not found - clipboard copy skipped"
    CLIPBOARD_SUCCESS=false
fi

# ============================================================================
# STEP 5: Show Windows notification
# ============================================================================

if command -v powershell.exe &> /dev/null; then
    powershell.exe -Command "
        Add-Type -AssemblyName System.Windows.Forms
        \$notification = New-Object System.Windows.Forms.NotifyIcon
        \$notification.Icon = [System.Drawing.SystemIcons]::Information
        \$notification.BalloonTipIcon = [System.Windows.Forms.ToolTipIcon]::Info
        \$notification.BalloonTipText = 'Context filled! Prompt ready in clipboard. Press Ctrl+V in new conversation OR just start new conversation - it will auto-resume.'
        \$notification.BalloonTipTitle = 'Claude Code - Session Continuation Ready'
        \$notification.Visible = \$true
        \$notification.ShowBalloonTip(10000)
    " 2>/dev/null &
    echo "✅ Windows notification sent"
fi

# ============================================================================
# STEP 6: Summary
# ============================================================================

echo ""
echo "╔════════════════════════════════════════════════════════════════════╗"
echo "║         🤖 FULLY AUTOMATED CONTINUATION ACTIVATED                 ║"
echo "╚════════════════════════════════════════════════════════════════════╝"
echo ""
echo "✨ OPTION 1: ZERO-TOUCH AUTO-RESUME (Recommended)"
echo "   → Just start a new Claude Code conversation anytime"
echo "   → Claude will automatically detect and offer to resume"
echo "   → No manual steps required!"
echo ""
echo "✨ OPTION 2: IMMEDIATE CONTINUATION"
if [ "$CLIPBOARD_SUCCESS" = true ]; then
    echo "   → Prompt is already in your clipboard"
    echo "   → Open new Claude Code conversation"
    echo "   → Press Ctrl+V to paste"
else
    echo "   → Run: cat $BACKUP_FILE"
    echo "   → Copy the output"
    echo "   → Start new conversation and paste"
fi
echo ""
echo "📁 Backup saved: $BACKUP_FILE"
echo "💾 Memory saved: .serena/memories/ACTIVE_SESSION_CONTINUATION.md"
echo ""
echo "⏰ Session ended: $DATE_READABLE"
echo ""

# Final success log
echo "=== PreCompact hook completed successfully at $(date) ===" >&2
echo "✅ All operations completed. Memory ready for auto-resume." >&2

