-- supabase/migrations/20251219_003_fix_override_commissions_rls.sql
-- Fix RLS policy for override_commissions table - correct column names
--
-- Schema: override_commissions has:
--   - override_agent_id: the upline receiving the override commission
--   - base_agent_id: the downline whose policy generated the override

-- Drop any failed policy attempt
DROP POLICY IF EXISTS "Uplines can view downline override_commissions" ON override_commissions;

-- Create correct policy for override_commissions
-- An upline can view override_commissions if:
-- 1. They are the override recipient (override_agent_id = auth.uid())
-- 2. They are an upline of the base agent (the agent whose production generated it)
CREATE POLICY "Uplines can view downline override_commissions"
ON override_commissions FOR SELECT
TO authenticated
USING (
  -- User can view their own overrides (they are the recipient)
  override_agent_id = auth.uid()
  OR
  -- Or user is an upline of the base agent whose production generated the override
  is_upline_of(base_agent_id)
);

COMMENT ON POLICY "Uplines can view downline override_commissions" ON override_commissions IS 'Allows viewing overrides: own received overrides OR overrides generated by downline production';

-- Verify the policy was created
DO $$
DECLARE
  policy_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO policy_count
  FROM pg_policies
  WHERE tablename = 'override_commissions'
  AND policyname = 'Uplines can view downline override_commissions';

  IF policy_count = 1 THEN
    RAISE NOTICE '✅ Override commissions upline policy created successfully';
  ELSE
    RAISE WARNING '❌ Failed to create override commissions policy';
  END IF;
END $$;
