// scripts/elco-rules-data.ts
// Manually extracted ELCO Golden Eagle Impairment Table rules
// Source: Guide ID 411a35b1-b2bb-49a9-9608-91f500815a81, Updated April 17, 2024

export interface ElcoRuleData {
  condition: string;
  conditionCode: string;
  lookback: string;
  lookbackYears: number; // 0 = Ever, -1 = Any/Current
  parameters: string;
  decision: "decline" | "standard" | "substandard" | "refer";
  tableRating: string; // e.g., 'D', 'F', 'H', 'none'
  medications: string;
  drugCombinations: string;
  notes: string;
}

export const ELCO_RULES: ElcoRuleData[] = [
  // Page 1
  {
    condition: "Activities of Daily Living",
    conditionCode: "impacted_adls",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Unable to perform any of the activities listed",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes:
      "bathing, toileting, eating, dressing, walking, maintaining continence or transferring from bed to chair",
  },
  {
    condition: "AIDS / HIV",
    conditionCode: "aids_hiv",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Truvada, Retrovir",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Alcohol abuse",
    conditionCode: "alcohol_abuse",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Serentil, Vivitrol, Thiamine, Vitamin B1",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Alzheimers / Memory loss",
    conditionCode: "alzheimers",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Donepezil, Memantine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Amyotrophic Lateral Sclerosis (ALS)",
    conditionCode: "als",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Radicava",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Angina",
    conditionCode: "angina_cardiac_chest_pain",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "",
    decision: "substandard",
    tableRating: "H",
    medications: "Nitrostat, Isordil, Nitroglycerin",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Angioplasty",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Ongoing symptoms",
    decision: "decline",
    tableRating: "none",
    medications: "Nitrostat, Isordil, Nitroglycerin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Angioplasty",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Full recovery",
    decision: "substandard",
    tableRating: "H",
    medications: "Clopidogrel",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Aortic aneurysm",
    conditionCode: "aneurysm",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Metropolol, Amlodopine Besylate",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Asthma",
    conditionCode: "asthma",
    lookback: "Any",
    lookbackYears: -1,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "Symbicort, Ventolin",
    drugCombinations: "",
    notes: "",
  },

  // Page 2 - Atrial Fibrillation
  {
    condition: "Atrial Fibrillation (AFib)",
    conditionCode: "afib",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Mild (no episodes in last 12 months)",
    decision: "substandard",
    tableRating: "F",
    medications: "Eliquis, Xarelto",
    drugCombinations:
      "Combination of anticoagulant (Eliquis/Xarelto) with beta blocker (e.g. Metropolol) or calcium channel blockers (e.g. Diltiazem) = Decline",
    notes: "Table 4-6",
  },
  {
    condition: "Atrial Fibrillation (AFib)",
    conditionCode: "afib",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Moderate (less than 4 episodes in last 12 months)",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Atrial Fibrillation (AFib)",
    conditionCode: "afib",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters:
      "Severe (more than 4 episodes or hospital treatment in the last 12 months)",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Autism",
    conditionCode: "autism",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Mild (IQ over 50, no other physical or mental illness)",
    decision: "substandard",
    tableRating: "F",
    medications: "Risperdal",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Autism",
    conditionCode: "autism",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Otherwise",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Auto racing",
    conditionCode: "auto_racing",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 3 - Bipolar, Blood Disorder, Cancer
  {
    condition: "Bipolar disorder",
    conditionCode: "bipolar",
    lookback: "Ever",
    lookbackYears: 0,
    parameters:
      "Under control with no manic episodes or hospitalization in last 12 months",
    decision: "substandard",
    tableRating: "F",
    medications: "Quetiapine, Lithium",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Bipolar disorder",
    conditionCode: "bipolar",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Other",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Blood Disorder",
    conditionCode: "blood_disorder",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Anemia Iron Deficiency",
    decision: "standard",
    tableRating: "none",
    medications: "Iron tablets",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Blood Disorder",
    conditionCode: "blood_disorder",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Other anemia",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Blood Disorder",
    conditionCode: "blood_disorder",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters:
      "Bleeding disorders - No episodes or hospital treatment in last 2 years",
    decision: "substandard",
    tableRating: "D",
    medications: "Amicar, Hemlibra",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Blood Disorder",
    conditionCode: "blood_disorder",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Other",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cancer",
    conditionCode: "cancer",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cancer",
    conditionCode: "cancer",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Excluding basal cell / squamous cell",
    decision: "substandard",
    tableRating: "H",
    medications: "Avastin, Tykerb",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cancer",
    conditionCode: "cancer",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Excluding basal cell / squamous cell - More than 1 occurrence",
    decision: "decline",
    tableRating: "none",
    medications: "Anastrozole",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cardiomyopathy",
    conditionCode: "cardiomyopathy",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Dexrazoxane",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cataract Treatment",
    conditionCode: "cataract_treatment",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 4 - Chest Pain, Chronic Bronchitis, Cirrhosis, CHF
  {
    condition: "Chest Pain",
    conditionCode: "chest_pain",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Fully investigated and confirmed as muscular only",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Chest Pain",
    conditionCode: "chest_pain",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Otherwise",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Chronic Bronchitis",
    conditionCode: "bronchitis_chronic",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Oxygen or hospital within last 3 years",
    decision: "decline",
    tableRating: "none",
    medications: "Oxygen",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Chronic Bronchitis",
    conditionCode: "bronchitis_chronic",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "> 1 course of steroids within last year",
    decision: "decline",
    tableRating: "none",
    medications: "Prednisone, Prednisolone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Chronic Bronchitis",
    conditionCode: "bronchitis_chronic",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Smoker",
    decision: "substandard",
    tableRating: "H",
    medications: "Prednisone, Prednisolone",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Chronic Bronchitis",
    conditionCode: "bronchitis_chronic",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "None of the above",
    decision: "substandard",
    tableRating: "F",
    medications: "Albuterol, Trelegy Ellipta, Atrovent",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Cirrhosis",
    conditionCode: "cirrhosis",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Ursodiol",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Confined to facility",
    conditionCode: "hospitalization_2_nights",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "3 or more times",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes:
      "hospital, nursing facility, convalescent care facility or mental facility",
  },
  {
    condition: "Congestive Heart Failure (CHF)",
    conditionCode: "congestive_heart_failure_chf",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Aldactone, Lasix",
    drugCombinations: "",
    notes: "",
  },

  // Page 5 - COPD, Coronary, Crohn's
  {
    condition: "COPD",
    conditionCode: "copd",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Oxygen or hospital within last 3 years",
    decision: "decline",
    tableRating: "none",
    medications: "Symbicort, Pulmicort, Spiriva",
    drugCombinations:
      "Combination of rescue inhalers paired with steroids such as Prednisone indicate severe COPD",
    notes: "",
  },
  {
    condition: "COPD",
    conditionCode: "copd",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "> 1 course of steroids within last year",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "COPD",
    conditionCode: "copd",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Smoker",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "COPD",
    conditionCode: "copd",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "None of the above",
    decision: "substandard",
    tableRating: "F",
    medications: "",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Coronary Artery Bypass",
    conditionCode: "cardiac_surgery",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Nitrostat",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Coronary Artery Disease",
    conditionCode: "coronary_artery_disease",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Nitrostat",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Crohns Disease",
    conditionCode: "crohns",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Surgery within the last 2 years",
    decision: "substandard",
    tableRating: "F",
    medications: "Sulfasalazine, Methotrexate",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Crohns Disease",
    conditionCode: "crohns",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Steroids within the last year",
    decision: "substandard",
    tableRating: "D",
    medications: "Prednisilone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Crohns Disease",
    conditionCode: "crohns",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Otherwise",
    decision: "standard",
    tableRating: "none",
    medications: "Sulfasalazine, Methotrexate",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Cystic Fibrosis",
    conditionCode: "cystic_fibrosis",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Symdeko",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Deep Vein Thrombosis",
    conditionCode: "blood_clots_no_complications",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 6 - Defibrillator, Dementia, Depression, Diabetes (first part)
  {
    condition: "Defibrillator implanted",
    conditionCode: "defibrillator",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Amiodarone, Lidocaine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Dementia / Senile dementia",
    conditionCode: "dementia",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Donepezil",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Depression",
    conditionCode: "depression",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "Sertraline, Trazodone, Duloxetine",
    drugCombinations:
      "Use of antipsychotics (e.g. Quetiapine) = Decline. Combinations with opioids (e.g. Oxycodone) = Substandard / Decline",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Amputation due to complications of diabetes",
    decision: "decline",
    tableRating: "none",
    medications: "Isoxsurpine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Insulin Use Prior to Age 40",
    decision: "decline",
    tableRating: "none",
    medications: "Humulin, Novolin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Diagnosed before age 25",
    decision: "substandard",
    tableRating: "F",
    medications: "Humulin, Novolin, Metformin",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Diabetic Coma",
    decision: "decline",
    tableRating: "none",
    medications: "Humulin, Metformin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Insulin Shock",
    decision: "decline",
    tableRating: "none",
    medications: "Humulin, Metformin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "No insulin - Nephropathy",
    decision: "decline",
    tableRating: "none",
    medications: "Metformin, Spironolactone",
    drugCombinations: "",
    notes: "",
  },

  // Page 7 - Diabetes (continued)
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "No insulin - Neuropathy",
    decision: "substandard",
    tableRating: "D",
    medications: "Metformin, Gabapentin",
    drugCombinations: "",
    notes: "Table 3-4",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "No insulin - Retinopathy",
    decision: "standard",
    tableRating: "none",
    medications: "Metformin, Trulicity",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "No insulin - No complications",
    decision: "standard",
    tableRating: "none",
    medications: "Metformin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "On Insulin - Nephropathy",
    decision: "decline",
    tableRating: "none",
    medications: "Humulin, Kerendia, Spironolactone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "On Insulin - Neuropathy",
    decision: "decline",
    tableRating: "none",
    medications: "Humulin, Gabapentin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "On Insulin - Retinopathy",
    decision: "substandard",
    tableRating: "F",
    medications: "Humulin, Trulicity",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Diabetes",
    conditionCode: "diabetes",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "On Insulin - No complications",
    decision: "substandard",
    tableRating: "D",
    medications: "Metformin, Glipizide, Humulin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Downs Syndrome",
    conditionCode: "down_syndrome",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Drug abuse",
    conditionCode: "drug_abuse",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Methadone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "DUI / DWI",
    conditionCode: "driving_offenses_duidwiowi",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Single conviction",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "DUI / DWI",
    conditionCode: "driving_offenses_duidwiowi",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Repeat conviction",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 8 - Edema, Emphysema, ESRD, Epilepsy, Felony
  {
    condition: "Edema / Fluid Retention",
    conditionCode: "edema_fluid_retention",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations:
      "Higher doses of diuretics (e.g. hydrochlorothiazide, furosemide) or longer-term treatments may indicate congestive heart failure or chronic kidney disease",
    notes: "",
  },
  {
    condition: "Emphysema",
    conditionCode: "emphysema",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Oxygen or hospital within last 3 years",
    decision: "decline",
    tableRating: "none",
    medications: "Oxygen",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Emphysema",
    conditionCode: "emphysema",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "> 1 course of steroids within last year",
    decision: "decline",
    tableRating: "none",
    medications: "Prednisone, Prednisolone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Emphysema",
    conditionCode: "emphysema",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Smoker",
    decision: "substandard",
    tableRating: "H",
    medications: "Prednisone, Prednisolone",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Emphysema",
    conditionCode: "emphysema",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "None of the above",
    decision: "substandard",
    tableRating: "F",
    medications: "Albuterol, Trelegy Ellipta, Atrovent",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "End Stage Renal Disease (ESRD) or Dialysis",
    conditionCode: "dialysis",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Fosrenol, Renvela",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Epilepsy",
    conditionCode: "epilepsy",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "substandard",
    tableRating: "D",
    medications: "Carbamazepine, Topiramate",
    drugCombinations: "",
    notes: "Table 3-4",
  },
  {
    condition: "Felony",
    conditionCode: "felony_charges",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Violent felony or alcohol / drug related",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 9 - Felony (continued), Hang Gliding, Heart conditions
  {
    condition: "Felony",
    conditionCode: "felony_charges",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Non violent & not drug / alcohol related",
    decision: "refer",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "Individual consideration",
  },
  {
    condition: "Hang Gliding",
    conditionCode: "hang_gliding",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Heart attack",
    conditionCode: "heart_attack",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Clopidogrel, Isordil",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Heart disease",
    conditionCode: "heart_disease",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Nitrostat, Isordil",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Heart surgery",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Valve replacement",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Nitrostat, Isordil",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Heart surgery",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Other surgery",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Heart transplant",
    conditionCode: "organ_transplant",
    lookback: "Any",
    lookbackYears: -1,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Cyclosporine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Heart valve replacement",
    conditionCode: "heart_valve_surgery",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Lopressor, Inderal",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Hepatitis A or E",
    conditionCode: "hepatitis_a_e",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Full Recovery",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Hepatitis B, C or D",
    conditionCode: "hepatitis_b_or_c",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Infergen, Rebetron",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Hernia repair",
    conditionCode: "hernia",
    lookback: "Any",
    lookbackYears: -1,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "High blood pressure / Hypertension",
    conditionCode: "high_blood_pressure",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Uncontrolled",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 10 - Hypertension (continued), Hodgkins, Hospice, Huntingtons, Kidney, Leukemia, Liver
  {
    condition: "High blood pressure / Hypertension",
    conditionCode: "high_blood_pressure",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Controlled",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations:
      "Combination of multiple anti-hypertensive drugs indicates potential control issues. Combinations including diuretics (e.g. furosemide / spironolactone) may indicate congestive heart failure",
    notes: "",
  },
  {
    condition: "Hodgkins Disease",
    conditionCode: "hodgkins_disease",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Keytruda, Opdivo",
    drugCombinations: "",
    notes: "",
  },
  {
    condition:
      "Hospitalized, confined to a bed or nursing facility; or receiving hospice care",
    conditionCode: "hospice",
    lookback: "Current",
    lookbackYears: -1,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Huntingtons Disease",
    conditionCode: "huntingtons_disease",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Austedo, Xenazine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Kidney Disease or Failure",
    conditionCode: "kidney_disease",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Chronic, including dialysis",
    decision: "decline",
    tableRating: "none",
    medications: "Renagel, Renvela",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Kidney Transplant",
    conditionCode: "organ_transplant",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Renagel, Renvela, Cyclosporine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Leukemia",
    conditionCode: "leukemia",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Arzerra, Sprycel",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Liver Disease",
    conditionCode: "liver_disease",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Not Hepatitis",
    decision: "decline",
    tableRating: "none",
    medications: "Acetylcysteine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Liver Failure",
    conditionCode: "liver_failure",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Acetylcysteine",
    drugCombinations: "",
    notes: "",
  },

  // Page 11 - Liver Transplant, Lou Gehrig's, Lymphoma, Melanoma, Mental incapacity, Motorcycles, Multiple myeloma, MS
  {
    condition: "Liver Transplant",
    conditionCode: "organ_transplant",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Acetylcysteine, Cyclosporine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Lou Gehrigs disease",
    conditionCode: "als",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Radicava",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Lymphoma",
    conditionCode: "non_hodgkins_lymphoma",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Methotrexate, Opdivo",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Melanoma",
    conditionCode: "melanoma_less_than_2mm_including_in_situ",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Keytruda, Cotellic",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Mental incapacity",
    conditionCode: "mental_incapacity",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Donepezil, Memantine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Motorcycles",
    conditionCode: "motorcycles",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Motor boats",
    conditionCode: "motor_boats",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Multiple myeloma",
    conditionCode: "multiple_myeloma",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Darzalex",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Multiple Sclerosis",
    conditionCode: "ms",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters:
      "Walking aids required/ no motor impairment - Diagnosed within 12 months",
    decision: "decline",
    tableRating: "none",
    medications: "Lemtrada, Gilenya",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Multiple Sclerosis",
    conditionCode: "ms",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Diagnosed 1 to 3 years ago",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Multiple Sclerosis",
    conditionCode: "ms",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Diagnosed over 3 years ago",
    decision: "substandard",
    tableRating: "F",
    medications: "",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Multiple Sclerosis",
    conditionCode: "ms",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Unable to walk",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Muscular dystrophy",
    conditionCode: "muscular_dystrophy",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Emflaza",
    drugCombinations: "",
    notes: "",
  },

  // Page 12 - Nausea, Opioid, Organ transplant, Organic brain syndrome, Oxygen Use, Pacemaker
  {
    condition: "Nausea",
    conditionCode: "nausea",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "Ondansetron prescribed by an oncologist = Decline",
    notes: "",
  },
  {
    condition: "Opioid Usage",
    conditionCode: "opioid_usage",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters:
      "Combination of opioid (e.g. Oxycodone) with Suboxone, Buprenorphine / Naloxone",
    decision: "decline",
    tableRating: "none",
    medications: "Hydrocodone-Acetaminophen, Tramadol HCl",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Opioid Usage",
    conditionCode: "opioid_usage",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Oxycodone dosage over 100mg / day",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Opioid Usage",
    conditionCode: "opioid_usage",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Oxycodone dosage 50mg - 100mg / day",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Opioid Usage",
    conditionCode: "opioid_usage",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Oxycodone dosage under 50mg / day",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Organ transplant (incl bone marrow transplant)",
    conditionCode: "organ_transplant",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Other than corneal",
    decision: "decline",
    tableRating: "none",
    medications: "Neoral, Prograf",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Organic brain syndrome",
    conditionCode: "cognitive_disorder",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Donepezil, Memantine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Oxygen Use",
    conditionCode: "oxygen_therapy",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Oxygen",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pacemaker implanted",
    conditionCode: "pacemaker",
    lookback: "1 Year",
    lookbackYears: 1,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Amiodarone, Sotalol",
    drugCombinations: "",
    notes: "",
  },

  // Page 13 - Pacemaker (continued), Pancreatitis, Paraplegia, Parasailing, Parkinsons, PVD
  {
    condition: "Pacemaker implanted",
    conditionCode: "pacemaker",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "With other cardiovascular disease",
    decision: "decline",
    tableRating: "none",
    medications: "Amiodarone, Sotalol",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pacemaker implanted",
    conditionCode: "pacemaker",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "No symptoms",
    decision: "substandard",
    tableRating: "H",
    medications: "Amiodarone, Sotalol",
    drugCombinations: "",
    notes: "Table 6-8",
  },
  {
    condition: "Pancreatitis",
    conditionCode: "chronic_pancreatitis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Chronic",
    decision: "decline",
    tableRating: "none",
    medications: "Creon",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pancreatitis",
    conditionCode: "pancreatitis_resolved",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Acute - Diagnosed within 2 years",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pancreatitis",
    conditionCode: "pancreatitis_resolved",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Diagnosed over 2 years ago",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Paraplegia",
    conditionCode: "paralysisspinal_cord_injury",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "substandard",
    tableRating: "H",
    medications: "Gabapentin",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Parasailing",
    conditionCode: "parasailing",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Parkinsons disease",
    conditionCode: "parkinsons",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Required surgery",
    decision: "decline",
    tableRating: "none",
    medications: "Ropinirole, Carbidopa",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Parkinsons disease",
    conditionCode: "parkinsons",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "> 1 limb affected",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Parkinsons disease",
    conditionCode: "parkinsons",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Age < 50",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Parkinsons disease",
    conditionCode: "parkinsons",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "None of the above",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Peripheral Vascular Disease",
    conditionCode: "peripheral_vascular",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Age under 65",
    decision: "substandard",
    tableRating: "D",
    medications: "Plavix, Cilostazol",
    drugCombinations: "",
    notes: "Table 3-4",
  },
  {
    condition: "Peripheral Vascular Disease",
    conditionCode: "peripheral_vascular",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Age 65 or older",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 14 - PTSD, Pulmonary conditions, Quadraplegia, RA, Schizophrenia, Sickle Cell, Stem cell, Stent, Stroke, Suicide
  {
    condition: "PTSD",
    conditionCode: "post_traumatic_stress_disorder_ptsd",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pulmonary Fibrosis",
    conditionCode: "pulmonary_fibrosis",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Ofev, Esbriet",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Pulmonary Hypertension",
    conditionCode: "pulmonary_hypertension",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "substandard",
    tableRating: "D",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Quadraplegia / Tetraplegia",
    conditionCode: "wheelchair_bound",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Gabapentin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Rheumatoid Arthritis",
    conditionCode: "rheumatoid_arthritis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "No incapacity",
    decision: "standard",
    tableRating: "none",
    medications: "Diclofenac, Ibuprofen",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Rheumatoid Arthritis",
    conditionCode: "rheumatoid_arthritis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Movement impacted",
    decision: "substandard",
    tableRating: "D",
    medications: "Methotrexate, Sulfasalazine, Prednisolone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Schizophrenia / schizoaffective disorder",
    conditionCode: "schizophrenia",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Seroquel, Thorazine",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Sickle Cell Treatment",
    conditionCode: "sickle_cell_anemia",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Stem cell treatment",
    conditionCode: "organ_transplant",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Stent",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Ongoing symptoms",
    decision: "decline",
    tableRating: "none",
    medications: "Nitrostat, Isordil, Nitroglycerin",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Stent",
    conditionCode: "cardiac_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "Full recovery",
    decision: "substandard",
    tableRating: "H",
    medications: "Clopidogrel",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Stroke",
    conditionCode: "stroke",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Eliquis, Xarelto, Clopidogrel",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Stroke",
    conditionCode: "stroke",
    lookback: "4 Years",
    lookbackYears: 4,
    parameters: "Full recovery",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Suicide Attempt",
    conditionCode: "suicide_attempt",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },

  // Page 15 - Systemic lupus, Terminal Illness, Tooth removal, TIA, Ulcerative Colitis, Ultralight Aircraft, Vascular Surgery
  {
    condition: "Systemic lupus",
    conditionCode: "lupus",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "substandard",
    tableRating: "H",
    medications: "Methotrexate",
    drugCombinations: "",
    notes: "Table 7-8",
  },
  {
    condition: "Terminal Illness",
    conditionCode: "terminal_illness",
    lookback: "Ever",
    lookbackYears: 0,
    parameters: "Life expectancy < 12 months",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Tooth or tonsil removal",
    conditionCode: "tooth_or_tonsil_removal",
    lookback: "Any",
    lookbackYears: -1,
    parameters: "",
    decision: "standard",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Transient Ischemic Attack (TIA)",
    conditionCode: "stroke",
    lookback: "1 Year",
    lookbackYears: 1,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Aspirin, Plavix",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Transient Ischemic Attack (TIA)",
    conditionCode: "stroke",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "More than 1 attack",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Transient Ischemic Attack (TIA)",
    conditionCode: "stroke",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Full recovery",
    decision: "substandard",
    tableRating: "H",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Ulcerative Colitis",
    conditionCode: "ulcerative_colitis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Surgery within the last 2 years",
    decision: "substandard",
    tableRating: "F",
    medications: "Humira",
    drugCombinations: "",
    notes: "Table 4-6",
  },
  {
    condition: "Ulcerative Colitis",
    conditionCode: "ulcerative_colitis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Steroids within the last year",
    decision: "substandard",
    tableRating: "D",
    medications: "Prednisilone",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Ulcerative Colitis",
    conditionCode: "ulcerative_colitis",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "Otherwise",
    decision: "standard",
    tableRating: "none",
    medications: "Humira",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Ultralight Aircraft",
    conditionCode: "ultralight_aircraft",
    lookback: "2 Years",
    lookbackYears: 2,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "",
    drugCombinations: "",
    notes: "",
  },
  {
    condition: "Vascular Surgery",
    conditionCode: "vascular_surgery",
    lookback: "3 Years",
    lookbackYears: 3,
    parameters: "",
    decision: "decline",
    tableRating: "none",
    medications: "Plavix, Cilostazol",
    drugCombinations: "",
    notes: "",
  },
];

// Conditions that need to be created if they don't exist
export const ADDITIONAL_CONDITIONS = [
  {
    code: "edema_fluid_retention",
    name: "Edema / Fluid Retention",
    category: "cardiovascular",
  },
  { code: "hepatitis_a_e", name: "Hepatitis A or E", category: "infectious" },
  { code: "auto_racing", name: "Auto Racing", category: "lifestyle" },
  { code: "hang_gliding", name: "Hang Gliding", category: "lifestyle" },
  { code: "motorcycles", name: "Motorcycle Use", category: "lifestyle" },
  { code: "motor_boats", name: "Motor Boat Use", category: "lifestyle" },
  { code: "parasailing", name: "Parasailing", category: "lifestyle" },
  {
    code: "ultralight_aircraft",
    name: "Ultralight Aircraft",
    category: "lifestyle",
  },
  { code: "nausea", name: "Nausea", category: "gastrointestinal" },
  { code: "opioid_usage", name: "Opioid Usage", category: "substance" },
  {
    code: "cataract_treatment",
    name: "Cataract Treatment",
    category: "medical_conditions",
  },
  {
    code: "tooth_or_tonsil_removal",
    name: "Tooth or Tonsil Removal",
    category: "medical_conditions",
  },
  {
    code: "vascular_surgery",
    name: "Vascular Surgery",
    category: "cardiovascular",
  },
  { code: "multiple_myeloma", name: "Multiple Myeloma", category: "cancer" },
];
