// scripts/kcl-medications-data.ts
// KCL Term Medication Exclusion List - Signature Term Express

export interface MedicationRule {
  medication: string;
  decision: "decline" | "refer";
  notes: string;
}

// CARRIER: Kansas City Life
export const CARRIER_ID = "beb4739d-6dd3-4b24-9621-8b33dc8b61eb";
export const PRODUCT_ID = "5daf0d4c-fd12-41bc-8daa-bc5262c2fae9"; // Signature Term
export const GUIDE_ID = "a8669ad4-6321-4b01-a291-ac842e5830c9";
export const IMO_ID = "ffffffff-ffff-ffff-ffff-ffffffffffff";

// Medications that result in DECLINE
export const DECLINE_MEDICATIONS: string[] = [
  "Abacavir",
  "Abilify",
  "Adcirca",
  "Aggrenox",
  "Alkeran",
  "Amiodarone",
  "Ampyra",
  "Antabuse",
  "Anoro Ellipta",
  "Aricept",
  "Arimidex",
  "Atripla",
  "Avonex",
  "Azilect",
  "Baraclude",
  "Betaseron",
  "Breo Ellipta",
  "Buprenorphine (Subutex)",
  "Calcium Acetate",
  "Campath",
  "Campral",
  "Caprelsa",
  "Carbidopa/Levodopa",
  "Casodex",
  "Cayston",
  "Cellcept",
  "Chlorpromazine Hcl",
  "Clozapine",
  "Cognex",
  "Combivir",
  "Comtan",
  "Copaxone",
  "Crixivan",
  "Cyclosporine",
  "Cytoxan",
  "Daklinza",
  "Daliresp",
  "Descovy",
  "Digitek",
  "Digoxin",
  "Dobutamine Hcl",
  "Donepezil",
  "Droxia",
  "Eldepryl",
  "Eligard",
  "Eliquis",
  "Eminase",
  "Enbrel",
  "Entresto",
  "Erythropoietin",
  "Epivir Hbv",
  "Ergoloid Mesylates",
  "Exelon",
  "Fanapt",
  "Femara",
  "Flecainide",
  "Fluorouracil",
  "Galantamine Hydrobromide",
  "Gammagard",
  "Gamunex",
  "Gengraf",
  "Genvoya",
  "Geodon",
  "Haldol",
  "Haloperidol",
  "Harvoni",
  "Hepsera",
  "Humira",
  "Hydrea",
  "Hydroxyurea",
  "Infergen",
  "Inspra",
  "Insulin",
  "Invega",
  "Invirase",
  "Isentress",
  "Kaletra",
  "Kalydeco",
  "Keytruda",
  "Lamictal",
  "Lanoxin",
  "Latuda",
  "Leucovorin Calcium",
  "Lexiva",
  "Limbitrol",
  "Lithium",
  "Megestrol Acetate (Megace)",
  "Mercaptopurine",
  "Methadone",
  "Methotrexate",
  "Mitomycin",
  "Morphine Sulfate",
  "Mycophenolate Mofetil",
  "Myfortic",
  "Nabi-Hb",
  "Naloxone Hcl",
  "Naltrexone Hcl",
  "Namenda",
  "Neupogen",
  "Nitroglycerin",
  "Odefsey",
  "Olysio",
  "Opdivo",
  "Panretin",
  "Pegasys",
  "Peg-Intron",
  "Perphenazine",
  "Pradaxa",
  "Prograf",
  "Quinidine",
  "Ranexa",
  "Razadyne",
  "Rebif",
  "Retrovir",
  "Revia",
  "Revlimid",
  "Rexulti",
  "Rhythmol",
  "Ribavirin",
  "Rilutek",
  "Risperdal",
  "Rituxan",
  "Sandimmune",
  "Saphris",
  "Seroquel",
  "Serzone",
  "Sinemet",
  "Sotalol",
  "Sovaldi",
  "Spiriva",
  "Stalevo",
  "Stribild",
  "Suboxone",
  "Sustiva",
  "Symbyax",
  "Tamoxifen",
  "Targretin",
  "Temodar",
  "Teslac",
  "Tikosyn",
  "Tolcapone",
  "Truvada",
  "Tudorza",
  "Tysabri",
  "Viracept",
  "Viramune",
  "Viread",
  "Vraylor",
  "Xarelto",
  "Xeljanz",
  "Yervoy",
  "Zenapax",
  "Zemplar",
  "Zerit",
  "Ziagen",
  "Zidovudine",
  "Zoladex",
  "Zyprexa",
];

// Medications that require INDIVIDUAL CONSIDERATION (refer)
export const REFER_MEDICATIONS: string[] = [
  "Carvedilol",
  "Clopidogrel",
  "Coreg",
  "Coumadin",
  "Enoxaparin Sodium",
  "Lovenox",
  "Prednisone",
  "Plavix",
  "Warfarin",
];

// Categorize medications by therapeutic class for better organization
export const MEDICATION_CATEGORIES: Record<string, string[]> = {
  "HIV/AIDS": [
    "Abacavir",
    "Atripla",
    "Combivir",
    "Crixivan",
    "Descovy",
    "Genvoya",
    "Invirase",
    "Isentress",
    "Kaletra",
    "Lexiva",
    "Odefsey",
    "Retrovir",
    "Stribild",
    "Sustiva",
    "Truvada",
    "Viracept",
    "Viramune",
    "Viread",
    "Zerit",
    "Ziagen",
    "Zidovudine",
    "Epivir Hbv",
  ],
  Hepatitis: [
    "Baraclude",
    "Daklinza",
    "Harvoni",
    "Hepsera",
    "Infergen",
    "Olysio",
    "Pegasys",
    "Peg-Intron",
    "Ribavirin",
    "Sovaldi",
    "Nabi-Hb",
  ],
  "Cancer/Oncology": [
    "Alkeran",
    "Arimidex",
    "Campath",
    "Casodex",
    "Cytoxan",
    "Droxia",
    "Eligard",
    "Femara",
    "Fluorouracil",
    "Hydrea",
    "Hydroxyurea",
    "Keytruda",
    "Leucovorin Calcium",
    "Mercaptopurine",
    "Methotrexate",
    "Mitomycin",
    "Opdivo",
    "Panretin",
    "Revlimid",
    "Rituxan",
    "Tamoxifen",
    "Targretin",
    "Temodar",
    "Teslac",
    "Yervoy",
    "Zoladex",
    "Neupogen",
    "Caprelsa",
    "Megestrol Acetate (Megace)",
  ],
  "Transplant/Immunosuppressant": [
    "Cellcept",
    "Cyclosporine",
    "Gengraf",
    "Mycophenolate Mofetil",
    "Myfortic",
    "Prograf",
    "Sandimmune",
    "Zenapax",
  ],
  "Multiple Sclerosis": ["Avonex", "Betaseron", "Copaxone", "Rebif", "Tysabri"],
  "Parkinson's/Movement Disorders": [
    "Azilect",
    "Carbidopa/Levodopa",
    "Comtan",
    "Eldepryl",
    "Sinemet",
    "Stalevo",
    "Tolcapone",
  ],
  "Dementia/Alzheimer's": [
    "Aricept",
    "Cognex",
    "Donepezil",
    "Exelon",
    "Galantamine Hydrobromide",
    "Namenda",
    "Razadyne",
    "Ergoloid Mesylates",
  ],
  "Psychiatric/Antipsychotic": [
    "Abilify",
    "Chlorpromazine Hcl",
    "Clozapine",
    "Fanapt",
    "Geodon",
    "Haldol",
    "Haloperidol",
    "Invega",
    "Latuda",
    "Limbitrol",
    "Lithium",
    "Perphenazine",
    "Rexulti",
    "Risperdal",
    "Saphris",
    "Seroquel",
    "Serzone",
    "Symbyax",
    "Vraylor",
    "Zyprexa",
    "Lamictal",
  ],
  "Cardiac/Heart": [
    "Aggrenox",
    "Amiodarone",
    "Digitek",
    "Digoxin",
    "Dobutamine Hcl",
    "Eliquis",
    "Eminase",
    "Entresto",
    "Flecainide",
    "Inspra",
    "Lanoxin",
    "Nitroglycerin",
    "Pradaxa",
    "Quinidine",
    "Ranexa",
    "Rhythmol",
    "Sotalol",
    "Tikosyn",
    "Xarelto",
  ],
  Pulmonary: [
    "Adcirca",
    "Anoro Ellipta",
    "Breo Ellipta",
    "Cayston",
    "Daliresp",
    "Kalydeco",
    "Spiriva",
    "Tudorza",
  ],
  "Autoimmune/Rheumatic": ["Enbrel", "Humira", "Xeljanz"],
  "Substance Abuse/Addiction": [
    "Antabuse",
    "Buprenorphine (Subutex)",
    "Campral",
    "Methadone",
    "Naloxone Hcl",
    "Naltrexone Hcl",
    "Revia",
    "Suboxone",
  ],
  "Neurological/ALS": ["Ampyra", "Rilutek"],
  "Pain/Opioid": ["Morphine Sulfate"],
  Diabetes: ["Insulin"],
  Kidney: ["Calcium Acetate", "Erythropoietin", "Zemplar"],
  Immunoglobulin: ["Gammagard", "Gamunex"],
};

// Individual consideration medications by reason
export const REFER_MEDICATION_DETAILS: Record<string, string> = {
  Carvedilol: "Beta blocker for heart failure/hypertension",
  Clopidogrel: "Antiplatelet for cardiovascular disease",
  Coreg: "Brand name for Carvedilol",
  Coumadin: "Warfarin brand - anticoagulant",
  "Enoxaparin Sodium": "Low molecular weight heparin",
  Lovenox: "Brand name for Enoxaparin",
  Prednisone: "Corticosteroid - depends on reason for use",
  Plavix: "Brand name for Clopidogrel",
  Warfarin: "Anticoagulant",
};

// All medication rules combined
export const ALL_MEDICATION_RULES: MedicationRule[] = [
  ...DECLINE_MEDICATIONS.map((med) => ({
    medication: med,
    decision: "decline" as const,
    notes: "Not eligible for Signature Term Express",
  })),
  ...REFER_MEDICATIONS.map((med) => ({
    medication: med,
    decision: "refer" as const,
    notes:
      REFER_MEDICATION_DETAILS[med] ||
      "Individual consideration - provide reason for medication on application",
  })),
];
