// scripts/moo-drug-exclusions-data.ts
// Mutual of Omaha - Prescription Drug Exclusions

// CARRIER: Mutual of Omaha
export const CARRIER_ID = "d619cc12-0a24-4242-9a2d-3dada1fb4b1e";
export const IMO_ID = "ffffffff-ffff-ffff-ffff-ffffffffffff";

// Guide IDs
export const GUIDE_IDS = {
  TERM_LIFE_IUL: "81f63b33-ad8d-4afd-926a-75da78b7ff53",
  LIVING_PROMISE: "10aafca1-77dc-4f4a-b6f5-4f0c557a2c2b",
};

// Product IDs
export const PRODUCT_IDS = {
  TERM_LIFE_EXPRESS: "1acbbee5-3cd4-4d47-9f2f-eb05d09f0023",
  IUL_EXPRESS: "3c227f86-4f5c-4c37-ac07-e8fa28c451c5",
  LIVING_PROMISE: "4b5f65d3-d4eb-4c9c-96ab-c3d8654d5378",
  LIVING_PROMISE_GRADED: "bd530cec-620a-4d5d-aea3-5af59c03dbae",
};

// ============================================================================
// TERM LIFE EXPRESS / IUL EXPRESS - All decline
// ============================================================================
export const TLE_IUL_DECLINE_MEDICATIONS: string[] = [
  "Abacavir",
  "Adcirca",
  "Aggrenox",
  "Alkeran",
  "Amiodarone",
  "Ampyra",
  "Anoro Ellipta",
  "Antabuse",
  "Aricept",
  "Arimidex",
  "Atripla",
  "Avonex",
  "Azilect",
  "Baraclude",
  "Betaseron",
  "Calcium Acetate",
  "Campath",
  "Campral",
  "Caprelsa",
  "Carbidopa/Levodopa",
  "Casodex",
  "Cellcept",
  "Chlorpromazine Hcl",
  "Clozapine",
  "Cognex",
  "Combivir",
  "Copaxone",
  "Crixivan",
  "Cyclosporine",
  "Cytoxan",
  "Daliresp",
  "Digitek",
  "Digoxin",
  "Dobutamine Hcl",
  "Donepezil",
  "Droxia",
  "Eligard",
  "Eliquis",
  "Enbrel",
  "Epivir Hbv",
  "Ergoloid Mesylates",
  "Exelon",
  "Femara",
  "Floxuridine",
  "Fluorouracil",
  "Galantamine Hydrobromide",
  "Gammagard",
  "Gamunex",
  "Gengraf",
  "Geodon",
  "Haldol",
  "Haloperidol",
  "Hepsera",
  "Humira",
  "Hydrea",
  "Hydroxyurea",
  "Infergen",
  "Invega",
  "Invirase",
  "Isentress",
  "Kalydeco",
  "Keytruda",
  "Lanoxin",
  "Latuda",
  "Leucovorin Calcium",
  "Lexiva",
  "Lithium",
  "Megestrol Acetate (Megace)",
  "Methadone",
  "Methotrexate",
  "Mitomycin",
  "Morphine Sulfate",
  "Mycophenolate Mofetil",
  "Myfortic",
  "Nabi-Hb",
  "Naloxone Hcl",
  "Naltrexone Hcl",
  "Namenda",
  "Neupogen",
  "Opdivo",
  "Panretin",
  "Pegasys",
  "Peg-Intron",
  "Perphenazine",
  "Prograf",
  "Ranexa",
  "Razadyne",
  "Rebif",
  "Retrovir",
  "Revia",
  "Revlimid",
  "Ribavirin",
  "Risperdal",
  "Rituxan",
  "Sandimmune",
  "Saphris",
  "Sinemet",
  "Spiriva",
  "Stalevo",
  "Stribild",
  "Suboxone",
  "Sustiva",
  "Symbyax",
  "Tamoxifen",
  "Targretin",
  "Teslac",
  "Tudorza",
  "Tysabri",
  "Viracept",
  "Viramune",
  "Viread",
  "Xarelto",
  "Xeljanz",
  "Zenapax",
  "Zerit",
  "Ziagen",
  "Zidovudine",
  "Zoladex",
  "Zyprexa",
];

// ============================================================================
// LIVING PROMISE - Three categories
// ============================================================================

// Decline for Living Promise (full decline, not eligible for graded either)
export const LP_DECLINE_MEDICATIONS: string[] = [
  "Abacavir",
  "Alkeran",
  "Atripla",
  "Aricept",
  "Campath",
  "Caprelsa",
  "Casodex",
  "Cellcept",
  "Cognex",
  "Combivir",
  "Crixivan",
  "Cyclosporine",
  "Cytoxan",
  "Donepezil",
  "Droxia",
  "Eligard",
  "Epivir Hbv",
  "Ergoloid Mesylates",
  "Exelon",
  "Floxuridine",
  "Fluorouracil",
  "Galantamine Hydrobromide",
  "Gammagard",
  "Gamunex",
  "Gengraf",
  "Hydrea",
  "Hydroxyurea",
  "Invirase",
  "Isentress",
  "Keytruda",
  "Leucovorin Calcium",
  "Lexiva",
  "Megace",
  "Megestrol Acetate (Megace)",
  "Mitomycin",
  "Mycophenolate",
  "Mofetil",
  "Myfortic",
  "Namenda",
  "Neupogen",
  "Opdivo",
  "Panretin",
  "Prograf",
  "Razadyne",
  "Retrovir",
  "Revlimid",
  "Rituxan",
  "Sandimmune",
  "Stribild",
  "Sustiva",
  "Targretin",
  "Teslac",
  "Viracept",
  "Viramune",
  "Viread",
  "Zenapax",
  "Zerit",
  "Ziagen",
  "Zidovudine",
  "Zoladex",
];

// May qualify for GRADED benefit (marked with * in source)
export const LP_GRADED_MEDICATIONS: string[] = [
  "Amiodarone",
  "Ampyra",
  "Anoro Ellipta",
  "Antabuse",
  "Avonex",
  "Azilect",
  "Betaseron",
  "Calcium Acetate",
  "Campral",
  "Carbidopa/Levodopa",
  "Chlorpromazine Hcl",
  "Clozapine",
  "Copaxone",
  "Daliresp",
  "Geodon",
  "Haldol",
  "Haloperidol",
  "Invega",
  "Latuda",
  "Lithium",
  "Naloxone Hcl",
  "Naltrexone Hcl",
  "Perphenazine",
  "Ranexa",
  "Rebif",
  "Revia",
  "Ribavirin",
  "Risperdal",
  "Saphris",
  "Sinemet",
  "Spiriva",
  "Stalevo",
  "Suboxone",
  "Symbyax",
  "Tudorza",
  "Zyprexa",
];

// Require additional information (refer for review)
export const LP_REFER_MEDICATIONS: string[] = [
  "Abilify",
  "Aggrenox",
  "Arimidex",
  "Baraclude",
  "Carvedilol",
  "Clopidogrel",
  "Coreg",
  "Coumadin",
  "Digitek",
  "Digoxin",
  "Eliquis",
  "Enoxaparin Sodium",
  "Femara",
  "Infergen",
  "Lanoxin",
  "Lovenox",
  "Pegasys",
  "Peg-Intron",
  "Plavix",
  "Pradaxa",
  "Seroquel",
  "Tamoxifen",
  "Truvada",
  "Warfarin",
  "Xarelto",
];

// Medication categories for grouping
export const MEDICATION_CATEGORIES: Record<string, string[]> = {
  "HIV/Antiretroviral": [
    "Abacavir",
    "Atripla",
    "Combivir",
    "Crixivan",
    "Epivir Hbv",
    "Invirase",
    "Isentress",
    "Lexiva",
    "Retrovir",
    "Stribild",
    "Sustiva",
    "Truvada",
    "Viracept",
    "Viramune",
    "Viread",
    "Zerit",
    "Ziagen",
    "Zidovudine",
  ],
  Hepatitis: [
    "Baraclude",
    "Hepsera",
    "Infergen",
    "Pegasys",
    "Peg-Intron",
    "Ribavirin",
  ],
  "Oncology/Cancer": [
    "Alkeran",
    "Arimidex",
    "Campath",
    "Caprelsa",
    "Casodex",
    "Cytoxan",
    "Droxia",
    "Eligard",
    "Femara",
    "Floxuridine",
    "Fluorouracil",
    "Hydrea",
    "Hydroxyurea",
    "Keytruda",
    "Leucovorin Calcium",
    "Megace",
    "Megestrol Acetate (Megace)",
    "Methotrexate",
    "Mitomycin",
    "Neupogen",
    "Opdivo",
    "Panretin",
    "Revlimid",
    "Rituxan",
    "Tamoxifen",
    "Targretin",
    "Teslac",
    "Zoladex",
  ],
  "Transplant/Immunosuppressant": [
    "Cellcept",
    "Cyclosporine",
    "Gengraf",
    "Mycophenolate Mofetil",
    "Myfortic",
    "Prograf",
    "Sandimmune",
    "Zenapax",
  ],
  "Multiple Sclerosis": ["Avonex", "Betaseron", "Copaxone", "Rebif", "Tysabri"],
  "Parkinson's/Movement": [
    "Azilect",
    "Carbidopa/Levodopa",
    "Sinemet",
    "Stalevo",
  ],
  "Dementia/Alzheimer's": [
    "Aricept",
    "Cognex",
    "Donepezil",
    "Ergoloid Mesylates",
    "Exelon",
    "Galantamine Hydrobromide",
    "Namenda",
    "Razadyne",
  ],
  "Psychiatric/Antipsychotic": [
    "Abilify",
    "Chlorpromazine Hcl",
    "Clozapine",
    "Geodon",
    "Haldol",
    "Haloperidol",
    "Invega",
    "Latuda",
    "Lithium",
    "Perphenazine",
    "Risperdal",
    "Saphris",
    "Seroquel",
    "Symbyax",
    "Zyprexa",
  ],
  Cardiac: [
    "Adcirca",
    "Aggrenox",
    "Amiodarone",
    "Carvedilol",
    "Clopidogrel",
    "Coreg",
    "Coumadin",
    "Digitek",
    "Digoxin",
    "Dobutamine Hcl",
    "Eliquis",
    "Enoxaparin Sodium",
    "Lanoxin",
    "Lovenox",
    "Plavix",
    "Pradaxa",
    "Ranexa",
    "Warfarin",
    "Xarelto",
  ],
  "Pulmonary/COPD": [
    "Anoro Ellipta",
    "Daliresp",
    "Kalydeco",
    "Spiriva",
    "Tudorza",
  ],
  "Autoimmune/Rheumatic": ["Enbrel", "Humira", "Xeljanz"],
  "Substance Abuse/Addiction": [
    "Antabuse",
    "Campral",
    "Methadone",
    "Naloxone Hcl",
    "Naltrexone Hcl",
    "Revia",
    "Suboxone",
  ],
  "Neurological/ALS": ["Ampyra"],
  "Pain/Opioid": ["Morphine Sulfate"],
  Immunoglobulin: ["Gammagard", "Gamunex"],
  Kidney: ["Calcium Acetate"],
};
