-- Migration: Create override_commissions Table
-- Purpose: Store override commissions earned by uplines from downline policy sales
-- Created: 2025-11-23

BEGIN;

-- ============================================
-- 1. CREATE OVERRIDE_COMMISSIONS TABLE
-- ============================================

CREATE TABLE IF NOT EXISTS override_commissions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Policy and agent relationships
  policy_id UUID NOT NULL REFERENCES policies(id) ON DELETE CASCADE,
  base_agent_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE,  -- who wrote the policy
  override_agent_id UUID NOT NULL REFERENCES user_profiles(id) ON DELETE CASCADE, -- who earns the override

  -- Hierarchy tracking
  hierarchy_depth INTEGER NOT NULL CHECK (hierarchy_depth > 0), -- 1 = immediate upline, 2 = upline's upline, etc.

  -- Commission calculation details
  base_comp_level INTEGER NOT NULL, -- base agent's contract comp level (e.g., 100)
  override_comp_level INTEGER NOT NULL CHECK (override_comp_level > base_comp_level), -- upline's level (e.g., 120)
  carrier_id UUID NOT NULL REFERENCES carriers(id) ON DELETE RESTRICT,
  product_id UUID REFERENCES products(id) ON DELETE SET NULL,
  policy_premium DECIMAL(12,2) NOT NULL CHECK (policy_premium >= 0),

  -- Calculated commission amounts (from comp_guide lookups)
  base_commission_amount DECIMAL(12,2) NOT NULL CHECK (base_commission_amount >= 0), -- what downline earned
  override_commission_amount DECIMAL(12,2) NOT NULL CHECK (override_commission_amount >= 0), -- difference (upline - downline)

  -- Advance tracking (same structure as base commissions)
  advance_months INTEGER DEFAULT 9 CHECK (advance_months >= 0),
  months_paid INTEGER DEFAULT 0 CHECK (months_paid >= 0),
  earned_amount DECIMAL(12,2) DEFAULT 0 CHECK (earned_amount >= 0),
  unearned_amount DECIMAL(12,2) DEFAULT 0 CHECK (unearned_amount >= 0),

  -- Chargeback tracking
  chargeback_amount DECIMAL(12,2) DEFAULT 0 CHECK (chargeback_amount >= 0),
  chargeback_date DATE,
  chargeback_reason TEXT,

  -- Status lifecycle (same as base commissions)
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'earned', 'paid', 'charged_back', 'cancelled', 'clawback')),

  -- Payment tracking
  payment_date DATE,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================
-- 2. CREATE INDEXES FOR PERFORMANCE
-- ============================================

CREATE INDEX idx_override_commissions_policy ON override_commissions(policy_id);
CREATE INDEX idx_override_commissions_base_agent ON override_commissions(base_agent_id);
CREATE INDEX idx_override_commissions_override_agent ON override_commissions(override_agent_id);
CREATE INDEX idx_override_commissions_status ON override_commissions(status);
CREATE INDEX idx_override_commissions_hierarchy_depth ON override_commissions(hierarchy_depth);
CREATE INDEX idx_override_commissions_created_at ON override_commissions(created_at DESC);

-- Composite index for common query pattern: get overrides for agent by status
CREATE INDEX idx_override_commissions_agent_status
  ON override_commissions(override_agent_id, status);

-- ============================================
-- 3. CREATE UPDATED_AT TRIGGER
-- ============================================

CREATE OR REPLACE FUNCTION update_override_commissions_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_override_commissions_updated_at_trigger
  BEFORE UPDATE ON override_commissions
  FOR EACH ROW
  EXECUTE FUNCTION update_override_commissions_updated_at();

-- ============================================
-- 4. ENABLE ROW LEVEL SECURITY
-- ============================================

ALTER TABLE override_commissions ENABLE ROW LEVEL SECURITY;

-- ============================================
-- 5. CREATE RLS POLICIES
-- ============================================

-- Policy 1: Users can view override commissions they earn
CREATE POLICY "Users can view own override commissions" ON override_commissions
  FOR SELECT
  USING (auth.uid() = override_agent_id AND is_user_approved());

-- Policy 2: Users can view override commissions generated by their downlines
-- (Useful for transparency - downlines can see what overrides they generated for uplines)
CREATE POLICY "Users can view overrides from own policies" ON override_commissions
  FOR SELECT
  USING (auth.uid() = base_agent_id AND is_user_approved());

-- Policy 3: Admin can view all override commissions
CREATE POLICY "Admins can view all overrides" ON override_commissions
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
      AND auth.users.email = 'nick@nickneessen.com'
    )
  );

-- Policy 4: Only system triggers can INSERT override commissions (not users)
-- Users should not manually create override commissions
-- (Enforced by not having INSERT policy - only database triggers can insert)

-- Policy 5: Admin can update override commissions (for corrections)
CREATE POLICY "Admins can update override commissions" ON override_commissions
  FOR UPDATE
  USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
      AND auth.users.email = 'nick@nickneessen.com'
    )
  );

-- Policy 6: Admin can delete override commissions (for corrections)
CREATE POLICY "Admins can delete override commissions" ON override_commissions
  FOR DELETE
  USING (
    EXISTS (
      SELECT 1 FROM auth.users
      WHERE auth.users.id = auth.uid()
      AND auth.users.email = 'nick@nickneessen.com'
    )
  );

-- ============================================
-- 6. CREATE HELPER VIEW FOR OVERRIDE SUMMARY
-- ============================================

CREATE OR REPLACE VIEW override_commission_summary AS
SELECT
  override_agent_id,
  COUNT(*) as total_overrides,
  SUM(override_commission_amount) as total_override_amount,
  SUM(CASE WHEN status = 'pending' THEN override_commission_amount ELSE 0 END) as pending_amount,
  SUM(CASE WHEN status = 'earned' THEN override_commission_amount ELSE 0 END) as earned_amount,
  SUM(CASE WHEN status = 'paid' THEN override_commission_amount ELSE 0 END) as paid_amount,
  SUM(CASE WHEN status = 'charged_back' THEN chargeback_amount ELSE 0 END) as charged_back_amount,
  SUM(earned_amount) as total_earned,
  SUM(unearned_amount) as total_unearned
FROM override_commissions
GROUP BY override_agent_id;

-- RLS for view (inherits from base table policies)
ALTER VIEW override_commission_summary SET (security_invoker = true);

COMMIT;

-- ============================================
-- COMPLETION MESSAGE
-- ============================================

DO $$
BEGIN
    RAISE NOTICE '';
    RAISE NOTICE '===========================================';
    RAISE NOTICE 'Migration 2: override_commissions Created!';
    RAISE NOTICE '===========================================';
    RAISE NOTICE 'Created override_commissions table with:';
    RAISE NOTICE '  - policy_id, base_agent_id, override_agent_id';
    RAISE NOTICE '  - hierarchy_depth tracking';
    RAISE NOTICE '  - Commission calculation fields';
    RAISE NOTICE '  - Advance/chargeback lifecycle tracking';
    RAISE NOTICE '  - Status field (same as base commissions)';
    RAISE NOTICE '';
    RAISE NOTICE 'Created indexes for performance';
    RAISE NOTICE 'Created RLS policies:';
    RAISE NOTICE '  - Users see overrides they earn';
    RAISE NOTICE '  - Users see overrides from own policies';
    RAISE NOTICE '  - Admin sees all';
    RAISE NOTICE '  - Only triggers can INSERT (users cannot)';
    RAISE NOTICE '';
    RAISE NOTICE 'Created override_commission_summary view';
    RAISE NOTICE '===========================================';
END $$;
