-- supabase/migrations/20260217132825_fix_rls_policies_to_authenticated.sql
--
-- Phase 3: Change TO public → TO authenticated on 342 RLS policies
--
-- PostgreSQL default for CREATE POLICY without a TO clause is TO public,
-- which means ALL roles including anon. This migration restricts these
-- policies to the authenticated role only.
--
-- Safety analysis:
-- All 342 policies have conditions that depend on auth.uid() either directly
-- or via helper functions (is_admin, is_imo_admin, is_super_admin, is_user_approved,
-- is_upline_of, get_my_imo_id, get_my_agency_id, is_agency_owner, can_manage_workflows,
-- has_role, has_permission, is_admin_user, is_imo_admin_for, is_staff_role).
-- These all return false/NULL when auth.uid() is NULL (anon), so anonymous users
-- already get zero access. This change simply skips policy evaluation for anon.
--
-- 25 policies intentionally KEPT as TO public:
--   - 6 policies with condition "true" (genuinely public data: app_config, landing_page_settings,
--     permissions, role_permissions, roles, trigger_event_types)
--   - 4 policies with non-auth conditions (subscription_addons is_active, trigger_event_types
--     is_active, subscription_plans is_active, workflow_templates is_public)
--   - 1 policy explicitly allowing NULL auth.uid() (user_profiles allow_trigger_insert)
--   - 2 policies with user_id IS NULL branches (instagram_message_templates, workflow_rate_limits)
--   - 7 service_role-checking policies (dead code since service_role bypasses RLS)
--   - 5 policies with condition "false" (service_role-only tables)
--
-- 1 separate {anon} policy (recruiting_leads INSERT) is unaffected.
--
-- Impact: Zero access change. Pure security hardening + performance optimization.

ALTER POLICY "Agency owners can view credential metadata" ON public.agency_slack_credentials TO authenticated;
ALTER POLICY "IMO admins can manage credentials" ON public.agency_slack_credentials TO authenticated;
ALTER POLICY agent_contracts_delete_policy ON public.agent_contracts TO authenticated;
ALTER POLICY agent_contracts_insert_policy ON public.agent_contracts TO authenticated;
ALTER POLICY agent_contracts_select_policy ON public.agent_contracts TO authenticated;
ALTER POLICY agent_contracts_update_policy ON public.agent_contracts TO authenticated;
ALTER POLICY agent_state_licenses_delete_policy ON public.agent_state_licenses TO authenticated;
ALTER POLICY agent_state_licenses_insert_policy ON public.agent_state_licenses TO authenticated;
ALTER POLICY agent_state_licenses_select_policy ON public.agent_state_licenses TO authenticated;
ALTER POLICY agent_state_licenses_update_policy ON public.agent_state_licenses TO authenticated;
ALTER POLICY agent_writing_numbers_delete_policy ON public.agent_writing_numbers TO authenticated;
ALTER POLICY agent_writing_numbers_insert_policy ON public.agent_writing_numbers TO authenticated;
ALTER POLICY agent_writing_numbers_select_policy ON public.agent_writing_numbers TO authenticated;
ALTER POLICY agent_writing_numbers_update_policy ON public.agent_writing_numbers TO authenticated;
ALTER POLICY "Users can manage own campaigns" ON public.bulk_email_campaigns TO authenticated;
ALTER POLICY "Users can manage recipients for own campaigns" ON public.bulk_email_recipients TO authenticated;
ALTER POLICY "IMO admins can create acceptance rules" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "IMO admins can update acceptance rules" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "IMO admins can view draft acceptance rules" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Users can delete acceptance rules for their IMO" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Users can insert acceptance rules for their IMO" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Users can update acceptance rules for their IMO" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Users can view acceptance rules for their IMO" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Users can view approved acceptance rules in their IMO" ON public.carrier_condition_acceptance TO authenticated;
ALTER POLICY "Agents can view own contracts" ON public.carrier_contracts TO authenticated;
ALTER POLICY "Staff can manage contracts" ON public.carrier_contracts TO authenticated;
ALTER POLICY "Admins can delete criteria" ON public.carrier_underwriting_criteria TO authenticated;
ALTER POLICY "Admins can insert criteria" ON public.carrier_underwriting_criteria TO authenticated;
ALTER POLICY "Admins can update criteria" ON public.carrier_underwriting_criteria TO authenticated;
ALTER POLICY "Users can view own IMO criteria" ON public.carrier_underwriting_criteria TO authenticated;
ALTER POLICY "Approved users can manage chargebacks" ON public.chargebacks TO authenticated;
ALTER POLICY "Users can view own chargebacks" ON public.chargebacks TO authenticated;
ALTER POLICY "Approved users can create own clients" ON public.clients TO authenticated;
ALTER POLICY "Approved users can delete own clients" ON public.clients TO authenticated;
ALTER POLICY "Approved users can update own clients" ON public.clients TO authenticated;
ALTER POLICY "IMO admins can view all clients in own IMO" ON public.clients TO authenticated;
ALTER POLICY "Super admins can view all clients" ON public.clients TO authenticated;
ALTER POLICY "Uplines can view downline clients" ON public.clients TO authenticated;
ALTER POLICY "Users can CRUD own clients" ON public.clients TO authenticated;
ALTER POLICY "Users can view clients on their own policies" ON public.clients TO authenticated;
ALTER POLICY clients_delete_own ON public.clients TO authenticated;
ALTER POLICY clients_delete_policy ON public.clients TO authenticated;
ALTER POLICY clients_insert_own ON public.clients TO authenticated;
ALTER POLICY clients_insert_policy ON public.clients TO authenticated;
ALTER POLICY clients_select_own_only ON public.clients TO authenticated;
ALTER POLICY clients_update_own ON public.clients TO authenticated;
ALTER POLICY clients_update_policy ON public.clients TO authenticated;
ALTER POLICY "Approved users can delete own commissions" ON public.commissions TO authenticated;
ALTER POLICY commissions_update_admin_simple ON public.commissions TO authenticated;
ALTER POLICY commissions_update_own_simple ON public.commissions TO authenticated;
ALTER POLICY "Users can manage own communication prefs" ON public.communication_preferences TO authenticated;
ALTER POLICY "Approved users can manage constants" ON public.constants TO authenticated;
ALTER POLICY "Enable read access for all users" ON public.constants TO authenticated;
ALTER POLICY contract_documents_delete_policy ON public.contract_documents TO authenticated;
ALTER POLICY contract_documents_insert_policy ON public.contract_documents TO authenticated;
ALTER POLICY contract_documents_select_policy ON public.contract_documents TO authenticated;
ALTER POLICY contract_documents_update_policy ON public.contract_documents TO authenticated;
ALTER POLICY "Users can view their IMO daily_sales_logs" ON public.daily_sales_logs TO authenticated;
ALTER POLICY "Users can delete own labels" ON public.email_labels TO authenticated;
ALTER POLICY "Users can insert own labels" ON public.email_labels TO authenticated;
ALTER POLICY "Users can update own labels" ON public.email_labels TO authenticated;
ALTER POLICY "Users can view own labels" ON public.email_labels TO authenticated;
ALTER POLICY "System can manage email queue" ON public.email_queue TO authenticated;
ALTER POLICY "Users can view their queued emails" ON public.email_queue TO authenticated;
ALTER POLICY "Admins can manage all quotas" ON public.email_quota_tracking TO authenticated;
ALTER POLICY "Users can insert own quota" ON public.email_quota_tracking TO authenticated;
ALTER POLICY "Users can update own quota" ON public.email_quota_tracking TO authenticated;
ALTER POLICY "Users can view own quota" ON public.email_quota_tracking TO authenticated;
ALTER POLICY "Users can manage own scheduled emails" ON public.email_scheduled TO authenticated;
ALTER POLICY "Users can delete own signatures" ON public.email_signatures TO authenticated;
ALTER POLICY "Users can insert own signatures" ON public.email_signatures TO authenticated;
ALTER POLICY "Users can update own signatures" ON public.email_signatures TO authenticated;
ALTER POLICY "Users can view own signatures" ON public.email_signatures TO authenticated;
ALTER POLICY "Users can delete own snippets" ON public.email_snippets TO authenticated;
ALTER POLICY "Users can insert own snippets" ON public.email_snippets TO authenticated;
ALTER POLICY "Users can update own snippets" ON public.email_snippets TO authenticated;
ALTER POLICY "Users can view own snippets" ON public.email_snippets TO authenticated;
ALTER POLICY email_templates_delete ON public.email_templates TO authenticated;
ALTER POLICY email_templates_insert ON public.email_templates TO authenticated;
ALTER POLICY email_templates_select ON public.email_templates TO authenticated;
ALTER POLICY email_templates_update ON public.email_templates TO authenticated;
ALTER POLICY "Users can delete own threads" ON public.email_threads TO authenticated;
ALTER POLICY "Users can insert own threads" ON public.email_threads TO authenticated;
ALTER POLICY "Users can update own threads" ON public.email_threads TO authenticated;
ALTER POLICY "Users can view own threads" ON public.email_threads TO authenticated;
ALTER POLICY "Users can view tracking for own emails" ON public.email_tracking_events TO authenticated;
ALTER POLICY "Users can view links for own emails" ON public.email_tracking_links TO authenticated;
ALTER POLICY "Admins can manage triggers" ON public.email_triggers TO authenticated;
ALTER POLICY "Users can view own watch subscriptions" ON public.email_watch_subscriptions TO authenticated;
ALTER POLICY expense_templates_delete_own ON public.expense_templates TO authenticated;
ALTER POLICY expense_templates_insert_own ON public.expense_templates TO authenticated;
ALTER POLICY expense_templates_select_own ON public.expense_templates TO authenticated;
ALTER POLICY expense_templates_update_own ON public.expense_templates TO authenticated;
ALTER POLICY "Approved users can create own expenses" ON public.expenses TO authenticated;
ALTER POLICY "Approved users can delete own expenses" ON public.expenses TO authenticated;
ALTER POLICY "Approved users can update own expenses" ON public.expenses TO authenticated;
ALTER POLICY "IMO admins can view all expenses in own IMO" ON public.expenses TO authenticated;
ALTER POLICY "Super admins can view all expenses" ON public.expenses TO authenticated;
ALTER POLICY "Uplines can view downline expenses" ON public.expenses TO authenticated;
ALTER POLICY "Users can CRUD own expenses" ON public.expenses TO authenticated;
ALTER POLICY expenses_delete_own ON public.expenses TO authenticated;
ALTER POLICY expenses_insert_own ON public.expenses TO authenticated;
ALTER POLICY expenses_select_own_only ON public.expenses TO authenticated;
ALTER POLICY expenses_update_own ON public.expenses TO authenticated;
ALTER POLICY gmail_integrations_delete ON public.gmail_integrations TO authenticated;
ALTER POLICY gmail_integrations_insert ON public.gmail_integrations TO authenticated;
ALTER POLICY gmail_integrations_select ON public.gmail_integrations TO authenticated;
ALTER POLICY gmail_integrations_update ON public.gmail_integrations TO authenticated;
ALTER POLICY gmail_sync_log_select ON public.gmail_sync_log TO authenticated;
ALTER POLICY "Admins can update any invitation" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Admins can view all invitations" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Authenticated users can send invitations" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Invitees can accept or deny invitations" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Inviters can cancel their pending invitations" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Users can view invitations sent to them" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY "Users can view invitations they sent" ON public.hierarchy_invitations TO authenticated;
ALTER POLICY instagram_conversations_delete ON public.instagram_conversations TO authenticated;
ALTER POLICY instagram_conversations_insert ON public.instagram_conversations TO authenticated;
ALTER POLICY instagram_conversations_select ON public.instagram_conversations TO authenticated;
ALTER POLICY instagram_conversations_update ON public.instagram_conversations TO authenticated;
ALTER POLICY instagram_integrations_delete ON public.instagram_integrations TO authenticated;
ALTER POLICY instagram_integrations_insert ON public.instagram_integrations TO authenticated;
ALTER POLICY instagram_integrations_select ON public.instagram_integrations TO authenticated;
ALTER POLICY instagram_integrations_update ON public.instagram_integrations TO authenticated;
ALTER POLICY instagram_templates_delete_personal ON public.instagram_message_templates TO authenticated;
ALTER POLICY instagram_templates_insert_personal ON public.instagram_message_templates TO authenticated;
ALTER POLICY instagram_templates_update_personal ON public.instagram_message_templates TO authenticated;
ALTER POLICY instagram_messages_insert ON public.instagram_messages TO authenticated;
ALTER POLICY instagram_messages_select ON public.instagram_messages TO authenticated;
ALTER POLICY instagram_scheduled_delete ON public.instagram_scheduled_messages TO authenticated;
ALTER POLICY instagram_scheduled_insert ON public.instagram_scheduled_messages TO authenticated;
ALTER POLICY instagram_scheduled_select ON public.instagram_scheduled_messages TO authenticated;
ALTER POLICY instagram_scheduled_update ON public.instagram_scheduled_messages TO authenticated;
ALTER POLICY template_categories_delete ON public.instagram_template_categories TO authenticated;
ALTER POLICY template_categories_insert ON public.instagram_template_categories TO authenticated;
ALTER POLICY template_categories_select ON public.instagram_template_categories TO authenticated;
ALTER POLICY template_categories_update ON public.instagram_template_categories TO authenticated;
ALTER POLICY instagram_usage_select ON public.instagram_usage_tracking TO authenticated;
ALTER POLICY landing_page_settings_imo_admin_all ON public.landing_page_settings TO authenticated;
ALTER POLICY landing_page_settings_super_admin_all ON public.landing_page_settings TO authenticated;
ALTER POLICY "Enable insert for users based on user_id" ON public.lead_purchases TO authenticated;
ALTER POLICY "Users can create threads" ON public.message_threads TO authenticated;
ALTER POLICY "Users can update their threads" ON public.message_threads TO authenticated;
ALTER POLICY "Users can view their threads" ON public.message_threads TO authenticated;
ALTER POLICY "Users can send messages" ON public.messages TO authenticated;
ALTER POLICY "Users can update thread messages" ON public.messages TO authenticated;
ALTER POLICY "Users can view thread messages" ON public.messages TO authenticated;
ALTER POLICY "Users can manage own notification prefs" ON public.notification_preferences TO authenticated;
ALTER POLICY "Users can delete their own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can update their own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Users can view their own notifications" ON public.notifications TO authenticated;
ALTER POLICY "Recruiters can insert onboarding phases for their recruits" ON public.onboarding_phases TO authenticated;
ALTER POLICY "Recruiters can update their recruits' onboarding phases" ON public.onboarding_phases TO authenticated;
ALTER POLICY "Recruiters can view their recruits' onboarding phases" ON public.onboarding_phases TO authenticated;
ALTER POLICY "Users can view their own onboarding phases" ON public.onboarding_phases TO authenticated;
ALTER POLICY "Admins can delete override commissions" ON public.override_commissions TO authenticated;
ALTER POLICY "Admins can insert override commissions" ON public.override_commissions TO authenticated;
ALTER POLICY "Admins can update override commissions" ON public.override_commissions TO authenticated;
ALTER POLICY "Admins can view all override commissions" ON public.override_commissions TO authenticated;
ALTER POLICY "Users can view overrides from own policies" ON public.override_commissions TO authenticated;
ALTER POLICY "Users can view own override commissions" ON public.override_commissions TO authenticated;
ALTER POLICY "Authenticated users can delete phase checklist items" ON public.phase_checklist_items TO authenticated;
ALTER POLICY "Authenticated users can insert phase checklist items" ON public.phase_checklist_items TO authenticated;
ALTER POLICY "Authenticated users can update phase checklist items" ON public.phase_checklist_items TO authenticated;
ALTER POLICY "Authenticated users can view phase checklist items" ON public.phase_checklist_items TO authenticated;
ALTER POLICY policies_delete_own ON public.policies TO authenticated;
ALTER POLICY policies_insert_own ON public.policies TO authenticated;
ALTER POLICY policies_update_own ON public.policies TO authenticated;
ALTER POLICY "Admins can manage commission overrides" ON public.product_commission_overrides TO authenticated;
ALTER POLICY "Users can delete rates for their IMO" ON public.product_rate_table TO authenticated;
ALTER POLICY "Users can insert rates for their IMO" ON public.product_rate_table TO authenticated;
ALTER POLICY "Users can update rates for their IMO" ON public.product_rate_table TO authenticated;
ALTER POLICY "Users can view rates for their IMO" ON public.product_rate_table TO authenticated;
ALTER POLICY "Users can insert outcomes for their IMO" ON public.recommendation_outcomes TO authenticated;
ALTER POLICY "Users can update outcomes for their IMO" ON public.recommendation_outcomes TO authenticated;
ALTER POLICY "Users can view outcomes for their IMO" ON public.recommendation_outcomes TO authenticated;
ALTER POLICY "Admins can manage all invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Recruiters can create invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Recruiters can delete own invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Recruiters can update own invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Recruiters can view own invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Uplines can view downline invitations" ON public.recruit_invitations TO authenticated;
ALTER POLICY "Super admins can view all branding settings" ON public.recruiting_page_settings TO authenticated;
ALTER POLICY "Users can delete own branding settings" ON public.recruiting_page_settings TO authenticated;
ALTER POLICY "Users can insert own branding settings" ON public.recruiting_page_settings TO authenticated;
ALTER POLICY "Users can update own branding settings" ON public.recruiting_page_settings TO authenticated;
ALTER POLICY "Users can view own branding settings" ON public.recruiting_page_settings TO authenticated;
ALTER POLICY scheduling_integrations_delete_own ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_insert_own ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_select_for_recruit ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_select_imo_admin ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_select_own ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_select_upline ON public.scheduling_integrations TO authenticated;
ALTER POLICY scheduling_integrations_update_own ON public.scheduling_integrations TO authenticated;
ALTER POLICY "Approved users can create own settings" ON public.settings TO authenticated;
ALTER POLICY "Approved users can delete own settings" ON public.settings TO authenticated;
ALTER POLICY "Approved users can update own settings" ON public.settings TO authenticated;
ALTER POLICY "Approved users can view own settings" ON public.settings TO authenticated;
ALTER POLICY "Users can CRUD own settings" ON public.settings TO authenticated;
ALTER POLICY slack_channel_configs_delete ON public.slack_channel_configs TO authenticated;
ALTER POLICY slack_channel_configs_insert ON public.slack_channel_configs TO authenticated;
ALTER POLICY slack_channel_configs_select ON public.slack_channel_configs TO authenticated;
ALTER POLICY slack_channel_configs_update ON public.slack_channel_configs TO authenticated;
ALTER POLICY slack_integrations_delete ON public.slack_integrations TO authenticated;
ALTER POLICY slack_integrations_insert ON public.slack_integrations TO authenticated;
ALTER POLICY slack_integrations_select ON public.slack_integrations TO authenticated;
ALTER POLICY slack_integrations_update ON public.slack_integrations TO authenticated;
ALTER POLICY slack_messages_select ON public.slack_messages TO authenticated;
ALTER POLICY "Users can delete webhooks for their IMO" ON public.slack_webhooks TO authenticated;
ALTER POLICY "Users can insert webhooks for their IMO" ON public.slack_webhooks TO authenticated;
ALTER POLICY "Users can update webhooks for their IMO" ON public.slack_webhooks TO authenticated;
ALTER POLICY "Users can view webhooks for their IMO" ON public.slack_webhooks TO authenticated;
ALTER POLICY state_classifications_delete_policy ON public.state_classifications TO authenticated;
ALTER POLICY state_classifications_insert_policy ON public.state_classifications TO authenticated;
ALTER POLICY state_classifications_select_policy ON public.state_classifications TO authenticated;
ALTER POLICY state_classifications_update_policy ON public.state_classifications TO authenticated;
ALTER POLICY "Super admins can manage addons" ON public.subscription_addons TO authenticated;
ALTER POLICY subscription_events_admin_all ON public.subscription_events TO authenticated;
ALTER POLICY subscription_events_select_own ON public.subscription_events TO authenticated;
ALTER POLICY subscription_payments_admin_all ON public.subscription_payments TO authenticated;
ALTER POLICY subscription_payments_select_own ON public.subscription_payments TO authenticated;
ALTER POLICY "Super admins can create plan changes" ON public.subscription_plan_changes TO authenticated;
ALTER POLICY "Super admins can view plan changes" ON public.subscription_plan_changes TO authenticated;
ALTER POLICY "Super admins can update plans" ON public.subscription_plans TO authenticated;
ALTER POLICY subscription_plans_admin_all ON public.subscription_plans TO authenticated;
ALTER POLICY sync_hierarchy_root_all_policy ON public.sync_hierarchy_root TO authenticated;
ALTER POLICY system_audit_log_select_policy ON public.system_audit_log TO authenticated;
ALTER POLICY "Admins can manage event types" ON public.trigger_event_types TO authenticated;
ALTER POLICY "Only admins can manage trigger event types" ON public.trigger_event_types TO authenticated;
ALTER POLICY "System can insert recommendations" ON public.underwriting_session_recommendations TO authenticated;
ALTER POLICY "Users can delete recommendations for their sessions" ON public.underwriting_session_recommendations TO authenticated;
ALTER POLICY "Users can view recommendations for their accessible sessions" ON public.underwriting_session_recommendations TO authenticated;
ALTER POLICY usage_tracking_admin_all ON public.usage_tracking TO authenticated;
ALTER POLICY usage_tracking_insert_own ON public.usage_tracking TO authenticated;
ALTER POLICY usage_tracking_select_own ON public.usage_tracking TO authenticated;
ALTER POLICY usage_tracking_update_own ON public.usage_tracking TO authenticated;
ALTER POLICY "Authenticated users can insert activity log entries" ON public.user_activity_log TO authenticated;
ALTER POLICY "Recruiters can view their recruits' activity log" ON public.user_activity_log TO authenticated;
ALTER POLICY "Users can view their own activity log" ON public.user_activity_log TO authenticated;
ALTER POLICY "Recruiters can delete their recruits' documents" ON public.user_documents TO authenticated;
ALTER POLICY "Recruiters can insert documents for their recruits" ON public.user_documents TO authenticated;
ALTER POLICY "Recruiters can update their recruits' documents" ON public.user_documents TO authenticated;
ALTER POLICY "Recruiters can view their recruits' documents" ON public.user_documents TO authenticated;
ALTER POLICY "Users can delete their own documents" ON public.user_documents TO authenticated;
ALTER POLICY "Users can insert their own documents" ON public.user_documents TO authenticated;
ALTER POLICY "Users can update their own documents" ON public.user_documents TO authenticated;
ALTER POLICY "Users can view their own documents" ON public.user_documents TO authenticated;
ALTER POLICY "Users can insert attachments for emails they created" ON public.user_email_attachments TO authenticated;
ALTER POLICY "Users can view attachments for emails they can view" ON public.user_email_attachments TO authenticated;
ALTER POLICY "Users can delete own OAuth tokens" ON public.user_email_oauth_tokens TO authenticated;
ALTER POLICY "Users can insert own OAuth tokens" ON public.user_email_oauth_tokens TO authenticated;
ALTER POLICY "Users can update own OAuth tokens" ON public.user_email_oauth_tokens TO authenticated;
ALTER POLICY "Users can view own OAuth tokens" ON public.user_email_oauth_tokens TO authenticated;
ALTER POLICY user_emails_delete_admin ON public.user_emails TO authenticated;
ALTER POLICY user_emails_delete_own ON public.user_emails TO authenticated;
ALTER POLICY user_emails_insert_admin ON public.user_emails TO authenticated;
ALTER POLICY user_emails_insert_own ON public.user_emails TO authenticated;
ALTER POLICY user_emails_select_admin ON public.user_emails TO authenticated;
ALTER POLICY user_emails_select_own ON public.user_emails TO authenticated;
ALTER POLICY user_emails_select_recruiter ON public.user_emails TO authenticated;
ALTER POLICY user_emails_select_sent ON public.user_emails TO authenticated;
ALTER POLICY user_emails_update_admin ON public.user_emails TO authenticated;
ALTER POLICY user_emails_update_recipient ON public.user_emails TO authenticated;
ALTER POLICY user_emails_update_sender ON public.user_emails TO authenticated;
ALTER POLICY "Approved users can manage expense_categories" ON public.user_expense_categories TO authenticated;
ALTER POLICY "Users can insert own expense categories" ON public.user_expense_categories TO authenticated;
ALTER POLICY "Users can read own expense categories" ON public.user_expense_categories TO authenticated;
ALTER POLICY "Users can delete own mailbox settings" ON public.user_mailbox_settings TO authenticated;
ALTER POLICY "Users can insert own mailbox settings" ON public.user_mailbox_settings TO authenticated;
ALTER POLICY "Users can update own mailbox settings" ON public.user_mailbox_settings TO authenticated;
ALTER POLICY "Users can view own mailbox settings" ON public.user_mailbox_settings TO authenticated;
ALTER POLICY "Admins can delete user profiles" ON public.user_profiles TO authenticated;
ALTER POLICY "Admins can update all user profiles" ON public.user_profiles TO authenticated;
ALTER POLICY "Admins can view all user profiles" ON public.user_profiles TO authenticated;
ALTER POLICY "Recruiters can delete own recruits" ON public.user_profiles TO authenticated;
ALTER POLICY "Recruiters can update own recruits" ON public.user_profiles TO authenticated;
ALTER POLICY "Uplines can delete own recruits" ON public.user_profiles TO authenticated;
ALTER POLICY "Uplines can update own recruits" ON public.user_profiles TO authenticated;
ALTER POLICY "Users can view downline profiles" ON public.user_profiles TO authenticated;
ALTER POLICY agency_members_can_view_same_agency ON public.user_profiles TO authenticated;
ALTER POLICY delete_user_policy ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_admin ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_hierarchy ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_own ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_own_recruiter ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_own_upline ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_recruiter ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_select_view_only ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_update_admin ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_update_contracting ON public.user_profiles TO authenticated;
ALTER POLICY user_profiles_update_own ON public.user_profiles TO authenticated;
ALTER POLICY "Users can delete own slack preferences" ON public.user_slack_preferences TO authenticated;
ALTER POLICY "Users can insert own slack preferences" ON public.user_slack_preferences TO authenticated;
ALTER POLICY "Users can update own slack preferences" ON public.user_slack_preferences TO authenticated;
ALTER POLICY "Users can view own slack preferences" ON public.user_slack_preferences TO authenticated;
ALTER POLICY "Super admins can manage user addons" ON public.user_subscription_addons TO authenticated;
ALTER POLICY "Users can view own addons" ON public.user_subscription_addons TO authenticated;
ALTER POLICY user_subscriptions_admin_all ON public.user_subscriptions TO authenticated;
ALTER POLICY user_subscriptions_select_own ON public.user_subscriptions TO authenticated;
ALTER POLICY user_subscriptions_update_own ON public.user_subscriptions TO authenticated;
ALTER POLICY "IMO admins can view all targets in own IMO" ON public.user_targets TO authenticated;
ALTER POLICY "Super admins can view all targets" ON public.user_targets TO authenticated;
ALTER POLICY "Uplines can view downline targets" ON public.user_targets TO authenticated;
ALTER POLICY "Users can delete own targets" ON public.user_targets TO authenticated;
ALTER POLICY "Users can insert own targets" ON public.user_targets TO authenticated;
ALTER POLICY "Users can update own targets" ON public.user_targets TO authenticated;
ALTER POLICY "Users can view own targets" ON public.user_targets TO authenticated;
ALTER POLICY user_targets_admin_all ON public.user_targets TO authenticated;
ALTER POLICY "Super admins can view all usage" ON public.uw_wizard_usage TO authenticated;
ALTER POLICY "Users can view own usage" ON public.uw_wizard_usage TO authenticated;
ALTER POLICY "Super admins can view all usage logs" ON public.uw_wizard_usage_log TO authenticated;
ALTER POLICY "Users can view own usage logs" ON public.uw_wizard_usage_log TO authenticated;
ALTER POLICY "Admins/trainers can manage all workflow actions" ON public.workflow_actions TO authenticated;
ALTER POLICY "Users can manage actions for own workflows" ON public.workflow_actions TO authenticated;
ALTER POLICY "Users can manage actions for their workflows" ON public.workflow_actions TO authenticated;
ALTER POLICY "Users can view own email tracking" ON public.workflow_email_tracking TO authenticated;
ALTER POLICY "Users can view workflow events" ON public.workflow_events TO authenticated;
ALTER POLICY "Admins can manage rate limits" ON public.workflow_rate_limits TO authenticated;
ALTER POLICY "Admins/trainers can view all workflow runs" ON public.workflow_runs TO authenticated;
ALTER POLICY "System can create workflow runs" ON public.workflow_runs TO authenticated;
ALTER POLICY "System can update workflow runs" ON public.workflow_runs TO authenticated;
ALTER POLICY "Users can view runs for own workflows" ON public.workflow_runs TO authenticated;
ALTER POLICY "Users can view runs for their workflows" ON public.workflow_runs TO authenticated;
ALTER POLICY "Users can view runs of their workflows" ON public.workflow_runs TO authenticated;
ALTER POLICY "Users can create templates" ON public.workflow_templates TO authenticated;
ALTER POLICY "Users can delete own templates" ON public.workflow_templates TO authenticated;
ALTER POLICY "Users can update own templates" ON public.workflow_templates TO authenticated;
ALTER POLICY "Users can manage triggers for own workflows" ON public.workflow_triggers TO authenticated;
ALTER POLICY "Admins/trainers can delete all workflows" ON public.workflows TO authenticated;
ALTER POLICY "Admins/trainers can update all workflows" ON public.workflows TO authenticated;
ALTER POLICY "Admins/trainers can view all workflows" ON public.workflows TO authenticated;
ALTER POLICY "IMO admins can manage org templates" ON public.workflows TO authenticated;
ALTER POLICY "IMO members can view org templates" ON public.workflows TO authenticated;
ALTER POLICY "Super admins can manage all org templates" ON public.workflows TO authenticated;
ALTER POLICY "Users can create workflows" ON public.workflows TO authenticated;
ALTER POLICY "Users can create workflows if they have permission" ON public.workflows TO authenticated;
ALTER POLICY "Users can delete their own workflows" ON public.workflows TO authenticated;
ALTER POLICY "Users can update their own workflows" ON public.workflows TO authenticated;
ALTER POLICY "Users can view their workflows" ON public.workflows TO authenticated;
ALTER POLICY "Users can view workflows they created" ON public.workflows TO authenticated;
ALTER POLICY writing_number_history_insert_policy ON public.writing_number_history TO authenticated;
ALTER POLICY writing_number_history_select_policy ON public.writing_number_history TO authenticated;
